name: techxcel11
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  rive: ^0.9.1
  flutter_svg: ^1.1.6
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  image_picker: ^1.0.4 #+++
  cloud_firestore: ^4.9.3
  shared_preferences: ^2.2.2
  get: ^4.6.5
  curved_navigation_bar: ^1.0.3
  font_awesome_flutter: ^10.5.0
  google_fonts: ^4.0.4
  url_launcher: ^6.1.14
  hash: ^1.0.4
  keyboard_dismisser: ^3.0.0
  intl: ^0.18.1
  firebase_storage: ^11.3.1
  fluttertoast: ^8.2.2
  path: ^1.8.3
  path_provider: ^2.1.1
  syncfusion_flutter_calendar: ^23.1.42

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  lottie: ^2.6.0
  csc_picker: ^0.2.7
  email_validator: ^2.1.17
  multi_select_flutter: ^4.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
